<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>AM.UI.Localization</RootNamespace>
    <AssemblyName>AM.UI.Localization</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AM.Core\AM.Core.csproj" />
    <ProjectReference Include="..\AM.Core.Abstractions\AM.Core.Abstractions.csproj" />
  </ItemGroup>

</Project>
